### ISSUE TITLE
GitHubTeacher adds a hometown file

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/everyone-dec15#3]
Tell everyone about my hometown, Fuquay Varina, NC.
# Fuquay-Varina
- [x] Create a branch
- [x] Create a file
- [x] Add some commits
- [x] Open a pull request
- [x] Have some discussion
- [x] Merge pull requests

:tada: @patrickmckenna

**Comment by patrickmckenna** [comment]
Nice checklist, @githubteacher.
