### ISSUE TITLE
bschonec add a hometown file 

### ISSUE THREAD

**Issue by bschonec** [githubteacher/everyone-dec15#8]
Cincinnati, OH -- home of Skyline Chili.
# Cincinnati, OH
- [x] Create a branch
- [x] Create a file
- [x] Add some commits
- [x] Open pull request
- [x] Discuss
- [x] Merge pull request
- [ ] Everyone is now a Skyline fan!

**Comment by skwgriffin** [comment]
:+1: thumbs up from a Columbusian!
